spring.application.name=FintechGuard

# Connect to the Docker container
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

# Tell Spring to auto-create the queue if it doesn't exist
spring.rabbitmq.template.default-receive-queue=app-queue

# Crucial: This tells Spring to turn the Java Object into JSON automatically
spring.mvc.converters.preferred-json-mapper=jackson